### ISSUE TITLE
Bind host hard-coded to localhost

### ISSUE THREAD

**Issue by jacobdanovitch** [MrMarble/rotxy#1]
Hey, thanks for the cool project. I'm trying to use it in a Docker container and noticed the server is hard-coded to [bind to localhost](https://github.com/MrMarble/rotxy/blob/b6d91d87633b1f936e1c96f4a9e98d98665dba71/pkg/server/proxy.go#L29):

```go
func Listen(port int, iterator proxy.ProxyIterator) {
	// ...
	log.Println("Serving at port", port)
	err := http.ListenAndServe(fmt.Sprintf("localhost:%d", port), middleProxy)
	if err != nil {
		panic(err)
	}
}
```

It would be really helpful if this were configurable by the command line (to make something like `-H 0.0.0.0` possible). Any chance that would be possible?

**Comment by MrMarble** [comment]
Thank you for using it!
Just released a new version with your suggestion and verbose logging [v.0.2.0](https://github.com/MrMarble/rotxy/releases/tag/v0.2.0). 
I've also added a Dockerfile and published the image to the GitHub registry https://github.com/MrMarble/rotxy/pkgs/container/rotxy.

If you have any other issue or contribution, feel free to make it!
